config/routes.rb
Rails.application.routes.draw do
  root 'home#home_page'
  get '/home_page', to: 'home#home_page'
  get '/about', to: 'home#about'
  get '/interests', to: 'home#interests'
  get '/music', to: 'home#music'
  get '/work', to: 'home#work'

 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def about
      @name = "Tobia Cassandro"
      @dob = "14.02.1982"
      @email = "tobiacassandro@gmail.com"
      @address = "17 Woronzow Road, London, NW8 6BA"
   
  end 
  
  def work_experience
  end
  
  def interests 
  end
  
  def music
  end

  def home_page

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/about.html.erb
<div class="container">

<h4> WELCOME </h4>

<div class="about-me">

 <h1 class="name">< Tobia Cassandr<span class="blink">_</span> /></h1>

<p> <%=@dob %> </p>

<p><%= @email %> </p> 

<p> <%=@address %> </p>

</div>

</div>

app/views/home/home_page.html.erb
<h1>TOBIA CASSANDRO</h1>

app/views/home/interests.html.erb
<h1>TOBIA CASSANDRO</h1>



<div class="container">

<ul>

<li>Social media</li> 
<li>Technology</li>
<li>Gadgets</li>
<li>Film</li>
<li>Live Music</li>
<li>Football</li>

</ul>
</div>

app/views/home/music.html.erb
<h1>TOBIA CASSANDRO</h1>

<div class="container">


<p> 




</p>

</div>

app/views/home/work.html.erb
<h1>TOBIA CASSANDRO</h1>

            <h2>Objective</h2>

                <p>Creative entrepreneur, looking for a new challenge utilising my law qualifications and legal experience.  
Having spent recent years working independently, being entirely self-starting, and managing a successful business, I am now seeking a position in the legal profession. Bringing a varied skill set from design, retail, media and legal roles, I am eager for a fresh opportunity to focus my energy. </p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TOBIA CASSANDRO</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body class = "<%= params[:action] %>">

<nav>
<!-- LINK_TO HELPER, first argument is what you see displayed in the browser, the second argument the helper (look in rake routes!) that specifies the corresponding controller and action -->
<li> <%= link_to('HOME',root_path, class: 'nav-link')%> </li>
<li> <%= link_to('ABOUT',about_path, class: 'nav-link')%> </li>
<li> <%= link_to('INTERESTS',interests_path, class: 'nav-link')%> </li>
<li> <%= link_to('MUSIC',music_path, class: 'nav-link')%> </li>
<li> <%= link_to('WORK EXPERIENCE',work_path, class: 'nav-link')%> </li>

</nav>


<%= yield %>

</body>
</html>